require 'MARQ'
require 'MARQ/main'
require 'MARQ/CustomDS'
require 'MARQ/MADB'
require 'MARQ/annotations'
require 'progress-monitor'
require File.join(File.dirname(File.dirname(__FILE__)), 'rake_includes')


$platform       ||= ENV['platform']
$organism       ||= [$organism, ENV['organism'], nil].compact.first 
$dataset        ||= ENV['dataset']

def process_list
  list = {}
  organisms = $organism ? [$organism] : Organism.all(true)

  # Find candidate datasets
  case
  when $dataset
    list[$dataset] = [$dataset]
  when $platform
    list[$platform] = [$platform]
  else
    organisms.each do |organism|
      datasets = Dir.glob(File.join(CustomDS::customdir, organism) + '/*').select{|f| File.directory? f}.collect{|f| File.basename(f)}
      datasets.each do |dataset|
        list[dataset] = dataset 
      end
    end
  end
 
  return list
end

